add support for timeEnd in Annotation queries
As with other plugins, the column name is all-lowercase "timeend"; it is
optional.

Support using millis for "time" and "timeend", in addition to
epoch-seconds.

Allow "text" and "tags" to be omitted from query, instead of throwing
cryptic error like

  TypeError: Cannot read properties of undefined (reading 'v')

Also fix some unrelated but nearby typos in function names.